# Generated by Django 3.0.3 on 2020-02-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='output/demo.png', upload_to='output/'),
        ),
    ]
