# Generated by Django 3.0.3 on 2020-02-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='static/cards/noName.png', upload_to='static/cards'),
        ),
    ]
