<<<<<<< HEAD
# Generated by Django 3.0.3 on 2020-02-13 19:34
=======
# Generated by Django 3.0.3 on 2020-02-13 20:58
>>>>>>> e32b6aa47ae50dbdcdf5e704e63ab993dcc4d80a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
<<<<<<< HEAD
            field=models.ImageField(default='output/demo.png', upload_to='output/'),
=======
            field=models.ImageField(default='static/cards/noName.png', upload_to='static/cards'),
>>>>>>> e32b6aa47ae50dbdcdf5e704e63ab993dcc4d80a
        ),
    ]
