# Generated by Django 3.0.3 on 2020-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageGenerator', '0002_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imageSol',
            field=models.ImageField(default='static/cards/noName2.png', upload_to='static/cards'),
        ),
    ]
