# Generated by Django 3.0.3 on 2020-02-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageGenerator', '0004_image_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='data',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded',
            field=models.BooleanField(default=''),
        ),
    ]
