# Generated by Django 3.0.3 on 2020-02-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageGenerator', '0005_auto_20200214_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded',
            field=models.BooleanField(blank=True, default=''),
        ),
    ]
